#!/bin/bash

PROGNAME=`basename $0`
error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

set -eo pipefail

id -u gemfast &>/dev/null || useradd -m -U gemfast
groupadd -f gemfast &>/dev/null
usermod -a -G gemfast gemfast
rm -f /usr/bin/gemfast
ln -sf /opt/gemfast/bin/gemfast-server /usr/bin || error_exit "Cannot link gemfast-server to /usr/bin"
mkdir -p /etc/gemfast
mkdir -p /var/gemfast/db
chown -R gemfast:gemfast /opt/gemfast

if [ ! -f "/etc/gemfast/.env" ]; then
  cp /opt/gemfast/etc/gemfast/.env /etc/gemfast
fi
touch /etc/gemfast/filter.conf
chown -R gemfast:gemfast /var/gemfast
chown -R gemfast:gemfast /etc/gemfast

for sv in "caddy" "gemfast"
do
  cp "/opt/gemfast/systemd/$sv/$sv.service" /etc/systemd/system
  systemctl enable $sv
done

echo "Thank you for installing Gemfast Server! For help getting started visit https://gemfast.io/docs"

exit 0