#!/bin/bash

PROGNAME=`basename $0`
error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

set -eo pipefail

id -u gemfast &>/dev/null || useradd -m -U gemfast
groupadd -f gemfast &>/dev/null
usermod -a -G gemfast gemfast
rm -f /usr/bin/gemfast
ln -sf /opt/gemfast/bin/gemfast-server /usr/bin || error_exit "Cannot link gemfast-server to /usr/bin"
mkdir -p /etc/gemfast
mkdir -p /var/gemfast/db

if [ ! -f "/etc/gemfast/gemfast.hcl" ]; then
  cp /opt/gemfast/default/gemfast.hcl /etc/gemfast
fi

for d in "/var/gemfast" "/etc/gemfast" "/opt/gemfast"
do
  chown -R gemfast:gemfast $d
done

for sv in "caddy" "gemfast"
do
  cp "/opt/gemfast/systemd/$sv/$sv.service" /etc/systemd/system
  systemctl enable $sv
done

echo "Thank you for installing Gemfast Server! For help getting started visit https://gemfast.io/docs/installation/"

exit 0