#!/bin/sh

INSTALLER_DIR=/opt/gemfast
if [ -e $INSTALLER_DIR ]; then
  echo "removing $INSTALLER_DIR..."

  # have to do this dance of moving /opt/gemfast to a tmp dir since files may be in use
  tmp_dir="/opt/.gemfast.$$"
  # if we can't create the tmp_dir then fail hard to prevent any possible security hole
  (umask 077 && mkdir $tmp_dir) || exit 1
  # now we can clean up the tmp_dir we created safely
  mv $INSTALLER_DIR $tmp_dir
  # ignore errors which must be EBUSY issues, this may crate some litter, which may
  # be unavoidable
  rm -rf $tmp_dir || true
fi