"""Curated list of popular RubyGems used by the load generator."""

GEMS = [
    "rake", "rails", "activesupport", "activerecord", "actionpack", "actionview",
    "actionmailer", "actioncable", "activejob", "activemodel", "activestorage",
    "actionmailbox", "actiontext", "railties", "sprockets", "sprockets-rails",
    "puma", "unicorn", "thin", "webrick", "rack", "rack-test", "rack-protection",
    "rack-attack", "rack-cors", "rack-proxy", "rackup",
    "nokogiri", "nokogumbo", "loofah", "rails-html-sanitizer",
    "json", "multi_json", "oj", "yajl-ruby", "psych", "toml-rb",
    "sidekiq", "resque", "delayed_job", "sucker_punch", "good_job", "shoryuken",
    "devise", "warden", "omniauth", "omniauth-oauth2", "omniauth-google-oauth2",
    "omniauth-github", "doorkeeper", "pundit", "cancancan", "rolify",
    "pg", "mysql2", "sqlite3", "redis", "redis-rails", "redis-namespace", "bunny",
    "mongo", "mongoid", "elasticsearch", "elasticsearch-rails", "searchkick",
    "kaminari", "will_paginate", "pagy",
    "rspec", "rspec-rails", "rspec-core", "rspec-mocks", "rspec-expectations",
    "rspec-support", "minitest", "minitest-reporters", "test-unit",
    "factory_bot", "factory_bot_rails", "faker", "ffaker", "vcr", "webmock",
    "capybara", "selenium-webdriver", "cucumber", "cucumber-rails", "rails-controller-testing",
    "simplecov", "simplecov-html", "simplecov-lcov", "coveralls", "codeclimate-test-reporter",
    "rubocop", "rubocop-rails", "rubocop-rspec", "rubocop-performance", "rubocop-rake",
    "rubocop-minitest", "rubocop-ast", "standard",
    "reek", "fasterer", "flay", "flog", "brakeman", "bundler-audit", "ruby_audit",
    "yard", "rdoc", "kramdown", "redcarpet", "commonmarker", "asciidoctor",
    "byebug", "pry", "pry-byebug", "pry-rails", "pry-doc", "pry-stack_explorer",
    "debug", "ruby-debug-ide", "stackprof", "memory_profiler", "benchmark-ips",
    "rufo", "syntax_tree", "prettier_print",
    "httparty", "rest-client", "faraday", "faraday-net_http", "faraday-retry",
    "faraday-multipart", "faraday-follow_redirects", "typhoeus", "excon",
    "http", "net-http", "net-http-persistent", "down", "open-uri-cached",
    "aws-sdk-core", "aws-sdk-s3", "aws-sdk-sns", "aws-sdk-sqs", "aws-sdk-secretsmanager",
    "aws-sdk-ssm", "aws-sdk-dynamodb", "aws-sdk-cloudwatch", "aws-sdk-cloudwatchlogs",
    "google-cloud-storage", "google-cloud-pubsub", "google-cloud-firestore",
    "azure-storage-blob",
    "stripe", "braintree", "paypal-checkout-sdk", "twilio-ruby", "sendgrid-ruby",
    "mailgun-ruby", "postmark-rails", "mail", "mail-iso-2022-jp", "premailer-rails",
    "letter_opener", "letter_opener_web",
    "sentry-ruby", "sentry-rails", "sentry-sidekiq", "bugsnag", "rollbar",
    "honeybadger", "appsignal", "newrelic_rpm", "ddtrace", "scout_apm",
    "opentelemetry-sdk", "opentelemetry-api", "opentelemetry-exporter-otlp",
    "opentelemetry-instrumentation-all", "opentelemetry-instrumentation-rails",
    "opentelemetry-instrumentation-rack", "opentelemetry-instrumentation-net_http",
    "opentelemetry-instrumentation-sidekiq", "opentelemetry-instrumentation-pg",
    "prometheus-client", "yabeda", "yabeda-prometheus", "statsd-ruby",
    "lograge", "semantic_logger", "logstash-logger", "amazing_print", "awesome_print",
    "colorize", "rainbow", "tty-prompt", "tty-progressbar", "tty-spinner", "tty-table",
    "tty-command", "tty-screen", "tty-cursor", "pastel",
    "thor", "gli", "commander", "slop", "optimist", "dry-cli", "clamp",
    "dry-validation", "dry-struct", "dry-types", "dry-monads", "dry-container",
    "dry-system", "dry-configurable", "dry-events", "dry-effects", "dry-schema",
    "trailblazer", "reform", "cells", "interactor", "wisper", "aasm", "state_machines",
    "state_machines-activerecord", "paper_trail", "audited", "logidze",
    "draper", "active_decorator", "active_interaction", "active_model_serializers",
    "jsonapi-serializer", "fast_jsonapi", "blueprinter", "alba", "panko_serializer",
    "graphql", "graphql-batch", "graphiql-rails", "apollo_upload_server",
    "jbuilder", "jb",
    "view_component", "phlex", "phlex-rails", "tailwindcss-rails", "tailwindcss-ruby",
    "stimulus-rails", "turbo-rails", "importmap-rails", "jsbundling-rails",
    "cssbundling-rails", "propshaft", "dartsass-rails", "vite_ruby", "vite_rails",
    "image_processing", "mini_magick", "ruby-vips", "image_optim", "rmagick",
    "carrierwave", "shrine", "paperclip", "refile", "active_storage_validations",
    "redcarpet", "rouge", "coderay", "pygments.rb",
    "geocoder", "country_select", "countries", "timezone", "tzinfo", "tzinfo-data",
    "chronic", "chronic_duration", "groupdate", "month", "business_time",
    "money", "money-rails", "monetize", "eu_central_bank", "google_currency",
    "i18n", "i18n-tasks", "rails-i18n", "globalize", "mobility", "translatomatic",
    "concurrent-ruby", "parallel", "ruby-progressbar", "tqdm",
    "websocket-client-simple", "websocket-driver", "em-websocket", "faye-websocket",
    "puma-status",
    "rabbitmq-rabbit", "sneakers", "kafka-rb", "ruby-kafka", "racecar",
    "graphql-ruby", "neo4j",
    "validates_email_format_of", "valid_email2", "phony", "phonelib",
    "uuid", "securerandom", "ulid-ruby", "snowflake-id",
    "bcrypt", "argon2", "scrypt", "rbnacl", "openssl-extensions",
    "jwt", "jwk", "ruby-jwt-pro",
]
